
language: node_js
node_js:
  - "8"
  - "9"

env:
  global:
  - ENCRYPTION_LABEL: "9305f989d237"
  - COMMIT_AUTHOR_EMAIL: "gory.alexandre02@gmail.com"

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
  